/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/Home.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NSpace: typeof import('naive-ui')['NSpace']
    NTable: typeof import('naive-ui')['NTable']
  }
}
